### ISSUE TITLE
JavaScript/Input button not working 

### ISSUE THREAD

**Issue by Shirodubble** [Shirodubble/Test#1]
I dont know why, yet, hopefully this is the right place to get help, I'll see.. 
I'm creating a simple To-Do-List with a delete button but i dont know why it isn't working. Here is the code for adding the listpoint & delete button:

> document.getElementById('add').addEventListener('click',erstellen);
        function erstellen (){
            var inputvalue = document.getElementById('inputtext').value;
            var textli= document.createTextNode(inputvalue);
            var newli= document.createElement('li');
            newli.id='li';
            newli.appendChild(textli);
            liContainer.appendChild(newli);         
        }
        document.getElementById('add').addEventListener('click',delbutton);
        function delbutton (){
            var del = document.createElement('input');
            del.setAttribute('type', 'button');
            del.setAttribute('id', 'löschen');
            liContainer.appendChild(del);

It's my first time using this site so dont be mad if I missed something, but this should be the part where something is missing/wrong, I do see the button I just cant click it. Why is that? Tried different Id's since i saw a question on stackoverflow where someone had the same issue, but that didnt work, tried using a button instead of input, didnt work too (as expected).

**Comment by MrMischievousX** [comment]
This may help you
`document.getElementById("add").addEventListener("click", erstellen);
      function erstellen() {
        var liContainer = document.getElementById("liContainer");
        var inputvalue = document.getElementById("inputtext").value;
        var textli = document.createTextNode(inputvalue);
        var newli = document.createElement("li");
        newli.classList.add("li");
        newli.appendChild(textli);
        var del = document.createElement("input");
        del.classList.add("löschen");
        del.type = "button";
        del.value = "löschen";
        del.onclick = function () {
          this.previousSibling.remove();
          this.remove();
        };
        liContainer.appendChild(newli);
        liContainer.appendChild(del);
      }`

Remember every id should be unique if you want multiple ones go with class

**Comment by Shirodubble** [comment]
Thx @MrMischievousX , I already solved the problem though, finished that project too and am working on a memory right now ...giving me good headaches ;)
